model = "gpt-5.2-codex"
notify = [ "bash", "-c", "~/.codex/notify_macos.sh" ]
model_reasoning_effort = "medium"
personality = "pragmatic"

[features]
web_search_request = true

[mcp_servers.playwright]
command = "npx"
args = [ "@playwright/mcp@latest" ]
